
namespace Microsoft.Toolkit.Win32.UI.XamlApplication
{
    interface IXamlMetadataContainer
    {
        Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Markup.IXamlMetadataProvider> MetadataProviders { get; };
    };

    [default_interface]
    unsealed runtimeclass App : Windows.UI.Xaml.Application, IXamlMetadataContainer, Windows.Foundation.IClosable
    {
        App(Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Markup.IXamlMetadataProvider> providers);
        protected App();
        protected void Initialize();

        Windows.Foundation.IClosable WindowsXamlManager{ get; };
        Boolean IsDisposed { get; };
    }
}
